name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file
      
    - name: Debug project structure
      run: |
        echo "Current directory structure:"
        tree -L 3 || ls -R

    - name: Prepare _site directory
      run: |
        if [ -d "_site" ]; then
          echo "_site directory already exists"
          rm -rf _site/*
        else
          mkdir _site
        fi
        cp -r templates _site/
        cp app.py _site/
        cp .nojekyll _site/ || touch _site/.nojekyll
        echo "Contents of _site directory:"
        ls -R _site

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: site-content
        path: _site
        if-no-files-found: warn

    - name: Debug if upload fails
      if: failure()
      run: |
        echo "Upload artifact step failed. Current directory structure:"
        tree -L 3 || ls -R
        echo "Contents of _site directory:"
        ls -la _site || echo "_site directory not found"