name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file
      
    - name: Debug project structure
      run: |
        echo "Current directory structure:"
        tree -L 3 || ls -R

    - name: Create static files
      run: |
        mkdir static
        cp -r templates static/
        cp app.py static/
        echo "Static files created. Directory structure:"
        tree static -L 3 || ls -R static

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static
        force_orphan: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: site-content
        path: static
        if-no-files-found: warn