name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file
      
    - name: Build site
      run: |
        # Add your build command here, for example:
        # python build_site.py

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true

    - name: Debug _site directory
      if: always()
      run: |
        echo "Contents of _site directory:"
        ls -R _site
        echo "Disk usage of _site directory:"
        du -sh _site

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: site-content
        path: _site
      continue-on-error: true

    - name: Debug upload artifact
      if: always()
      run: |
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Environment variables:"
        env