name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask openai python-dotenv requests beautifulsoup4

    - name: Prepare static files
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        mkdir _site
        cp -r templates _site/
        cp -r static _site/ || echo "No static directory found"
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" > .env
        python -c "
        import flask
        import os
        from dotenv import load_dotenv
        load_dotenv()
        app = flask.Flask(__name__)
        with app.app_context():
            with open('_site/index.html', 'w') as f:
                f.write(flask.render_template('index.html'))
        "
        touch _site/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true

    - name: Debug if any step fails
      if: failure()
      run: |
        echo "A step has failed. Current directory structure:"
        ls -R
        echo "Contents of _site directory:"
        ls -la _site || echo "_site directory not found"
        echo "Disk usage:"
        du -sh _site