name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file
      
    - name: Debug project structure before
      run: |
        echo "Current directory structure before creating static files:"
        tree -L 3 || ls -R

    - name: Create static files
      run: |
        mkdir -p static/templates
        cp -r templates/* static/templates/ || echo "No templates to copy"
        cp app.py static/ || echo "app.py not found"
        if [ -d "static" ]; then
          cp -r static/* static/ || echo "No additional static files to copy"
        fi
        echo "Static files created. Directory structure:"
        tree static -L 3 || ls -R static

    - name: Debug static directory
      run: |
        echo "Contents of static directory:"
        ls -la static
        echo "Contents of static/templates directory (if it exists):"
        ls -la static/templates || echo "static/templates directory not found"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static
        force_orphan: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: site-content
        path: static
        if-no-files-found: warn

    - name: Debug if upload fails
      if: failure()
      run: |
        echo "Upload artifact step failed. Current directory structure:"
        tree -L 3 || ls -R
        echo "Contents of static directory:"
        ls -la static || echo "static directory not found"