name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare deployment files
      run: |
        mkdir deploy
        cp -r templates deploy/
        cp app.py deploy/
        cp requirements.txt deploy/
        [ -f .env ] && cp .env deploy/ || echo "No .env file found"
        touch deploy/.nojekyll
        echo "Contents of deploy directory:"
        ls -R deploy

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: site-content
        path: |
          deploy/templates
          deploy/app.py
          deploy/requirements.txt
          deploy/.nojekyll
          deploy/.env
        if-no-files-found: warn

    - name: Debug if any step fails
      if: failure()
      run: |
        echo "A step has failed. Current directory structure:"
        ls -R
        echo "Contents of deploy directory:"
        ls -la deploy || echo "deploy directory not found"
        echo "Disk usage:"
        du -sh deploy
        echo "Environment variables:"
        env