name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file
      
    - name: Build site
      run: |
        python build_site.py  # Your actual build command
        echo "Build complete. Contents of current directory:"
        ls -R
        echo "Contents of _site directory (if it exists):"
        ls -R _site || echo "_site directory not found"

    - name: Debug build output
      run: |
        echo "Current directory contents:"
        ls -R

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true

    - name: Debug _site directory
      if: always()
      run: |
        echo "Contents of _site directory:"
        ls -R _site || echo "_site directory not found"
        echo "Disk usage of _site directory:"
        du -sh _site || echo "_site directory not found"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: site-content
        path: _site
      continue-on-error: true

    - name: Debug upload artifact
      if: always()
      run: |
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Environment variables:"
        env