name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug project structure
      run: |
        echo "Current directory structure:"
        tree -L 3 || ls -R

    - name: Prepare deployment files
      run: |
        mkdir deploy
        cp -r templates deploy/
        cp app.py deploy/
        touch deploy/.nojekyll
        echo "Contents of deploy directory:"
        ls -R deploy

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: site-content
        path: deploy
        if-no-files-found: warn

    - name: Debug if upload fails
      if: failure()
      run: |
        echo "Upload artifact step failed. Current directory structure:"
        tree -L 3 || ls -R
        echo "Contents of deploy directory:"
        ls -la deploy || echo "deploy directory not found"